version: '3.4'

services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: catalog/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - eburgan-dapr
  catalog-dapr:
    image: "daprio/daprd:1.6.0"
    command: [
      "./daprd",
     "-app-id", "catalog",
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ]
    volumes:
      - "./dapr/dc-components/:/components"
      - "./dapr/dc-config/:/config"
    depends_on:
      - catalog
    network_mode: "service:catalog"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - eburgan-dapr

  frontend-dapr:
    image: "daprio/daprd:1.6.0"
    command: [
      "./daprd",
     "-app-id", "frontend",
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ]
    volumes:
      - "./dapr/dc-components/:/components"
      - "./dapr/dc-config/:/config"
    depends_on:
      - frontend
    network_mode: "service:frontend"

  ordering:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: ordering/Dockerfile
    environment:
      - DAPR_HTTP_PORT=3500
    networks:
      - eburgan-dapr
  ordering-dapr:
    image: "daprio/daprd:1.6.0"
    command: [
      "./daprd",
     "-app-id", "ordering",
     "-app-port", "80",
     "-components-path", "/components",
     "-config", "/config/config.yaml"
     ]
    volumes:
      - "./dapr/dc-components/:/components"
      - "./dapr/dc-config/:/config"
    depends_on:
      - ordering
    network_mode: "service:ordering"

  redis:
    container_name: "redis_service"
    image: "redis:6.2-alpine"
    ports:
      - "6379"
    networks:
      - eburgan-dapr

  maildev:
    container_name: "maildev_service" 
    image: "maildev/maildev:1.1.0"
    ports:
      - "25"
      - "1080:80"
    networks:
      - eburgan-dapr
      
  zipkin:
    container_name: "zipkin_service"
    image: "openzipkin/zipkin:2.23.4"
    ports:
      - 9412:9411
    networks:
      - eburgan-dapr

networks:
  eburgan-dapr: